insert into skill_profissional (id_sp, id_pp, skill) values (1, 9, 'Interpersonal Skills');
insert into skill_profissional (id_sp, id_pp, skill) values (2, 9, 'Youth Mentoring');
insert into skill_profissional (id_sp, id_pp, skill) values (3, 2, 'Psychopharmacology');
insert into skill_profissional (id_sp, id_pp, skill) values (4, 10, 'Claims Handling');
insert into skill_profissional (id_sp, id_pp, skill) values (5, 7, 'Characterization');
insert into skill_profissional (id_sp, id_pp, skill) values (6, 10, 'HSE auditing');
insert into skill_profissional (id_sp, id_pp, skill) values (7, 3, 'FCRA');
insert into skill_profissional (id_sp, id_pp, skill) values (8, 10, 'IBM Rational Tools');
insert into skill_profissional (id_sp, id_pp, skill) values (9, 8, 'PwC TeamMate');
insert into skill_profissional (id_sp, id_pp, skill) values (10, 2, 'Blog Marketing');
insert into skill_profissional (id_sp, id_pp, skill) values (11, 10, 'FSMS');
insert into skill_profissional (id_sp, id_pp, skill) values (12, 3, 'Publications');
insert into skill_profissional (id_sp, id_pp, skill) values (13, 7, 'EBR');
insert into skill_profissional (id_sp, id_pp, skill) values (14, 5, 'QFD');
insert into skill_profissional (id_sp, id_pp, skill) values (15, 4, 'Cultural Awareness');
insert into skill_profissional (id_sp, id_pp, skill) values (16, 7, 'Investment Properties');
insert into skill_profissional (id_sp, id_pp, skill) values (17, 10, 'Technical Support');
insert into skill_profissional (id_sp, id_pp, skill) values (18, 6, 'Nortel DMS');
insert into skill_profissional (id_sp, id_pp, skill) values (19, 10, 'Loans');
insert into skill_profissional (id_sp, id_pp, skill) values (20, 4, 'WordPerfect');
insert into skill_profissional (id_sp, id_pp, skill) values (21, 1, 'MW');
insert into skill_profissional (id_sp, id_pp, skill) values (22, 7, 'Military Aviation');
insert into skill_profissional (id_sp, id_pp, skill) values (23, 9, 'IFM');
insert into skill_profissional (id_sp, id_pp, skill) values (24, 7, 'Scripting');
insert into skill_profissional (id_sp, id_pp, skill) values (25, 10, 'Store Operations');
insert into skill_profissional (id_sp, id_pp, skill) values (26, 7, 'Creative Non-fiction');
insert into skill_profissional (id_sp, id_pp, skill) values (27, 6, 'MBR');
insert into skill_profissional (id_sp, id_pp, skill) values (28, 4, 'FM');
insert into skill_profissional (id_sp, id_pp, skill) values (29, 1, 'Euphonium');
insert into skill_profissional (id_sp, id_pp, skill) values (30, 4, 'Tomcat');
insert into skill_profissional (id_sp, id_pp, skill) values (31, 6, 'CCNP');
insert into skill_profissional (id_sp, id_pp, skill) values (32, 6, 'PC building');
insert into skill_profissional (id_sp, id_pp, skill) values (33, 1, 'SDA');
insert into skill_profissional (id_sp, id_pp, skill) values (34, 2, 'Hibernate');
insert into skill_profissional (id_sp, id_pp, skill) values (35, 5, 'Blended Learning');
insert into skill_profissional (id_sp, id_pp, skill) values (36, 7, 'SAP SD');
insert into skill_profissional (id_sp, id_pp, skill) values (37, 7, 'Digital Printing');
insert into skill_profissional (id_sp, id_pp, skill) values (38, 4, 'Jigs');
insert into skill_profissional (id_sp, id_pp, skill) values (39, 8, 'Budgeting');
insert into skill_profissional (id_sp, id_pp, skill) values (40, 6, 'Analysis');
insert into skill_profissional (id_sp, id_pp, skill) values (41, 5, 'OAuth');
insert into skill_profissional (id_sp, id_pp, skill) values (42, 9, 'Tcpdump');
insert into skill_profissional (id_sp, id_pp, skill) values (43, 7, 'EFQM Excellence Model');
insert into skill_profissional (id_sp, id_pp, skill) values (44, 8, 'Erlang');
insert into skill_profissional (id_sp, id_pp, skill) values (45, 6, 'CCIP');
insert into skill_profissional (id_sp, id_pp, skill) values (46, 7, 'Smart GWT');
insert into skill_profissional (id_sp, id_pp, skill) values (47, 3, 'FCPA');
insert into skill_profissional (id_sp, id_pp, skill) values (48, 7, 'Jigs');
insert into skill_profissional (id_sp, id_pp, skill) values (49, 6, 'Family Medicine');
insert into skill_profissional (id_sp, id_pp, skill) values (50, 6, 'Theory');
insert into skill_profissional (id_sp, id_pp, skill) values (51, 7, 'SRAM');
insert into skill_profissional (id_sp, id_pp, skill) values (52, 4, 'Ozone Therapy');
insert into skill_profissional (id_sp, id_pp, skill) values (53, 6, 'CQE');
insert into skill_profissional (id_sp, id_pp, skill) values (54, 5, 'PKMS');
insert into skill_profissional (id_sp, id_pp, skill) values (55, 9, 'Sun One LDAP');
insert into skill_profissional (id_sp, id_pp, skill) values (56, 10, 'SketchUp');
insert into skill_profissional (id_sp, id_pp, skill) values (57, 4, 'Blackberry');
insert into skill_profissional (id_sp, id_pp, skill) values (58, 9, 'ePub');
insert into skill_profissional (id_sp, id_pp, skill) values (59, 8, 'Medicare');
insert into skill_profissional (id_sp, id_pp, skill) values (60, 1, 'FP');
insert into skill_profissional (id_sp, id_pp, skill) values (61, 7, 'HD Video');
insert into skill_profissional (id_sp, id_pp, skill) values (62, 5, 'Journal Entries');
insert into skill_profissional (id_sp, id_pp, skill) values (63, 10, 'RCP');
insert into skill_profissional (id_sp, id_pp, skill) values (64, 7, 'XACT');
insert into skill_profissional (id_sp, id_pp, skill) values (65, 7, 'Guided Reading');
insert into skill_profissional (id_sp, id_pp, skill) values (66, 4, 'Workplace Violence');
insert into skill_profissional (id_sp, id_pp, skill) values (67, 2, 'PTCRB');
insert into skill_profissional (id_sp, id_pp, skill) values (68, 7, 'Kaseya');
insert into skill_profissional (id_sp, id_pp, skill) values (69, 8, 'BSF');
insert into skill_profissional (id_sp, id_pp, skill) values (70, 2, 'AMBA AHB');
insert into skill_profissional (id_sp, id_pp, skill) values (71, 4, 'PTP');
insert into skill_profissional (id_sp, id_pp, skill) values (72, 10, 'Sage ERP X3');
insert into skill_profissional (id_sp, id_pp, skill) values (73, 7, 'BSD');
insert into skill_profissional (id_sp, id_pp, skill) values (74, 2, 'JSTL');
insert into skill_profissional (id_sp, id_pp, skill) values (75, 10, 'NT 4.0');
insert into skill_profissional (id_sp, id_pp, skill) values (76, 5, 'Static Timing Analysis');
insert into skill_profissional (id_sp, id_pp, skill) values (77, 3, 'JMP');
insert into skill_profissional (id_sp, id_pp, skill) values (78, 9, 'Ableton Live');
insert into skill_profissional (id_sp, id_pp, skill) values (79, 4, 'Payment by Results');
insert into skill_profissional (id_sp, id_pp, skill) values (80, 1, 'RhinoCAM');
insert into skill_profissional (id_sp, id_pp, skill) values (81, 2, 'Database Design');
insert into skill_profissional (id_sp, id_pp, skill) values (82, 8, 'NUnit');
insert into skill_profissional (id_sp, id_pp, skill) values (83, 3, 'Visual Studio');
insert into skill_profissional (id_sp, id_pp, skill) values (84, 7, 'Chamber Music');
insert into skill_profissional (id_sp, id_pp, skill) values (85, 4, 'eBay API');
insert into skill_profissional (id_sp, id_pp, skill) values (86, 8, 'Adult Education');
insert into skill_profissional (id_sp, id_pp, skill) values (87, 5, 'Telecom BSS');
insert into skill_profissional (id_sp, id_pp, skill) values (88, 3, 'DBT');
insert into skill_profissional (id_sp, id_pp, skill) values (89, 2, 'CD Mastering');
insert into skill_profissional (id_sp, id_pp, skill) values (90, 1, 'Systems Design');
insert into skill_profissional (id_sp, id_pp, skill) values (91, 10, 'GPS Devices');
insert into skill_profissional (id_sp, id_pp, skill) values (92, 5, 'Kontakt');
insert into skill_profissional (id_sp, id_pp, skill) values (93, 2, 'JSP');
insert into skill_profissional (id_sp, id_pp, skill) values (94, 8, 'NYMEX');
insert into skill_profissional (id_sp, id_pp, skill) values (95, 9, 'Hardware');
insert into skill_profissional (id_sp, id_pp, skill) values (96, 1, 'Orchestral Music');
insert into skill_profissional (id_sp, id_pp, skill) values (97, 7, 'DTD');
insert into skill_profissional (id_sp, id_pp, skill) values (98, 6, 'Efficent');
insert into skill_profissional (id_sp, id_pp, skill) values (99, 9, 'ebXML');
insert into skill_profissional (id_sp, id_pp, skill) values (100, 1, 'CME');

select * from skill_profissional;